"""Pydantic data models for the multi-agent equity research platform."""

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class ProvenanceRecord(BaseModel):
    """Lineage and provenance metadata for every data point or metric."""
    provider: str
    dataset_or_endpoint: str
    source_timestamp_utc: str
    retrieved_at_utc: str
    market_session: str = "closed"
    symbol: str
    currency: str = "USD"
    adjustment_status: Literal["split_adjusted", "unadjusted", "dividend_adjusted", "none"] = "unadjusted"
    request_parameters: Dict[str, Any] = Field(default_factory=dict)
    provider_record_id_or_url: str = ""


class SecurityIdentity(BaseModel):
    """Canonical security identity specification."""
    canonical_ticker: str
    exchange: str
    country: str  # US or CA
    currency: str  # USD or CAD
    company_name: str
    cik: Optional[str] = None
    figi: Optional[str] = None
    isin: Optional[str] = None
    cusip: Optional[str] = None
    primary_listing: bool = True
    cross_listed_ticker: Optional[str] = None
    cross_listed_exchange: Optional[str] = None
    asset_type: Literal["stock", "ETF"] = "stock"
    sector: str = "Unknown"
    industry: str = "Unknown"


class AgentTask(BaseModel):
    """Task metadata envelope for inter-agent communication."""
    job_id: str
    symbol: str
    agent: str
    task: str
    status: Literal["PENDING", "RUNNING", "COMPLETED", "FAILED", "REWORK_REQUIRED"] = "PENDING"
    inputs: List[str] = Field(default_factory=list)
    outputs: List[str] = Field(default_factory=list)
    evidence: List[Dict[str, Any]] = Field(default_factory=list)
    confidence: float = 1.0  # 0.0 to 1.0
    warnings: List[str] = Field(default_factory=list)
    data_gaps: List[str] = Field(default_factory=list)
    review_status: Literal["UNREVIEWED", "APPROVED", "REJECTED", "REWORK_REQUESTED"] = "UNREVIEWED"


class AgentOutput(BaseModel):
    """Structured artifact generated by specialist agents."""
    agent_name: str
    status: Literal["COMPLETED", "FAILED", "INSUFFICIENT_DATA"] = "COMPLETED"
    summary: str = ""
    facts: List[str] = Field(default_factory=list)
    calculations: Dict[str, Any] = Field(default_factory=dict)
    inferences: List[str] = Field(default_factory=list)
    uncertainties: List[str] = Field(default_factory=list)
    data_gaps: List[str] = Field(default_factory=list)
    citations: List[str] = Field(default_factory=list)
    confidence: float = 1.0


class JudgeReview(BaseModel):
    """Independent audit evaluation by a domain judge."""
    judge_name: str
    target_agent: str
    passed: bool
    score: float = 10.0  # 1.0 to 10.0 scale
    objections: List[str] = Field(default_factory=list)
    recommendations: List[str] = Field(default_factory=list)
    review_timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())


class ChiefReviewOutput(BaseModel):
    """Adversarial falsification critique by Chief Reviewer."""
    passed: bool
    critical_defects: List[str] = Field(default_factory=list)
    falsification_challenges: List[str] = Field(default_factory=list)
    unresolved_contradictions: List[str] = Field(default_factory=list)
    confidence_penalty: float = 0.0
    approved_for_delivery: bool = False


class ScoringResult(BaseModel):
    """Final calculated score breakdown."""
    sub_scores: Dict[str, float] = Field(default_factory=dict)  # 1.0 to 10.0
    base_ai_score: float = 5.0
    extended_ai_score: float = 5.0
    normalized_100_score: float = 50.0
    confidence_score: float = 1.0
    penalties: Dict[str, float] = Field(default_factory=dict)


class GateResult(BaseModel):
    """Result of an automated pipeline gate check."""
    gate_id: str
    gate_name: str
    passed: bool
    details: str
    remedy_action: Optional[str] = None
    checked_at_utc: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
